import os
import shutil
env = DefaultEnvironment()
include_dir = 'include/'
env.Append(CXXFLAGS=['-std=c++17','-D_GLIBCXX_USE_CXX11_ABI=0'], CPPPATH=[include_dir])
src_dir = 'src/'
target_dir = 'build/'
os.makedirs(target_dir, exist_ok=True)
env.VariantDir(target_dir, src_dir, duplicate=False)
def copy_source_files(target, source, env):
    for file in source:
        shutil.copy(file.abspath, target_dir)
env.Command(target_dir, src_dir, copy_source_files)
src_files = Glob(target_dir + '*.cpp')
lib = env.StaticLibrary(target='lib/lib.a', source=src_files)
Default(lib)