import os
import platform
arch = platform.machine()
if not os.path.exists('libtorch'):
    os.system('wget https://download.pytorch.org/libtorch/nightly/cpu/libtorch-shared-with-deps-latest.zip')
    os.system('unzip libtorch-shared-with-deps-latest.zip')
    os.system('rm -rf libtorch-shared-with-deps-latest.zip*')
env = Environment(
    CXXFLAGS=['-std=c++17','-D_GLIBCXX_USE_CXX11_ABI=0'],
    LINKFLAGS=['-Wl,-rpath=$ORIGIN/../libtorch/lib', '-Wl,-rpath=$ORIGIN'],
    CPPPATH= ['libtorch/include', 'libtorch/include/torch/csrc/api/include'],
    LIBPATH=['libtorch/lib'],
    LIBS=['torch', 'torch_cpu', 'c10'],
)
env.Program(target='build/ai', source='TorchNN.cpp')