name: CI
on:
  push:
    branches:
        - feature-GithubActions
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 
        uses: actions/checkout@v3
      - name: Build Application
        run: |
          scons
      - name: Upload artiffact
        uses: actions/download-artifact@v2
        with:
            name: Built_app
            path: app.tar
  test:
    runs-on : ubuntu-latest
    steps:
        - name: Download artifact
          uses: actions/download-artifact@v2
          with:
            name: app.tar
            path: /tmp
        - name: Tests
          run: |
            cd tests && cd build && ./tests


        